// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20230930141031_AddQuizResultToDb")]
    partial class AddQuizResultToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuizID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionID");

                    b.HasIndex("QuizID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            CorrectAnswer = 3,
                            OptionA = "Patates Kızartması",
                            OptionB = "Burger",
                            OptionC = "Döner",
                            OptionD = "Kuru Fasulye",
                            OptionE = "Makarna",
                            QuestionText = "En sevdiği yemek?",
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099")
                        },
                        new
                        {
                            QuestionID = 2,
                            CorrectAnswer = 1,
                            OptionA = "Pop",
                            OptionB = "Rap",
                            OptionC = "Rock",
                            OptionD = "Türk Halk Müziği",
                            OptionE = "Arabesk",
                            QuestionText = "En sevdiği müzik türü?",
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099")
                        },
                        new
                        {
                            QuestionID = 3,
                            CorrectAnswer = 4,
                            OptionA = "Uyuyarak",
                            OptionB = "Bilgisayar başında",
                            OptionC = "Yürüyüş yaparak",
                            OptionD = "Kitap okuyarak",
                            OptionE = "Arkadaşlarıyla buluşarak",
                            QuestionText = "Zamanını nasıl geçirir?",
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099")
                        },
                        new
                        {
                            QuestionID = 4,
                            CorrectAnswer = 2,
                            OptionA = "Kayıp para bulmak",
                            OptionB = "Tuttuğu takımın galibiyeti",
                            OptionC = "Süpriz hediye almak",
                            OptionD = "Alışveriş mağazasındaki indirimler",
                            OptionE = "Çekilişle telefon kazanmak",
                            QuestionText = "Onu en çok ne sevindirir?",
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099")
                        },
                        new
                        {
                            QuestionID = 5,
                            CorrectAnswer = 5,
                            OptionA = "Kırmızı",
                            OptionB = "Beyaz",
                            OptionC = "Siyah",
                            OptionD = "Sarı",
                            OptionE = "Mavi",
                            QuestionText = "Favori rengi ne?",
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099")
                        });
                });

            modelBuilder.Entity("Entities.Models.Quiz", b =>
                {
                    b.Property<Guid>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VisitLimit")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizID = new Guid("ea8b887f-042d-4c56-a034-68845aa34099"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 9, 30, 17, 10, 31, 782, DateTimeKind.Local).AddTicks(2191),
                            Name = "Havuz Soruları",
                            VisitLimit = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("QuizId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WrongAnswer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("Entities.Models.Question", b =>
                {
                    b.HasOne("Entities.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Entities.Models.QuizResult", b =>
                {
                    b.HasOne("Entities.Models.Quiz", "Quiz")
                        .WithMany("QuizResults")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Entities.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizResults");
                });
#pragma warning restore 612, 618
        }
    }
}
